Repository mr-robot-2008/html, pull requests merged in 2022-10, with the labels that each got.

#1 Create incredible
  incredible.html
Labels: hacktoberfest

#3 Revert "html code for hacktoberfest 2022"
  about_us.html
Labels: hacktoberfest2022 accepted

#4 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: hacktoberfest

#6 Added code and contribute file edited
  Best_Time_to_Buy_and_Sell_Stock.java
  CONTRIBUTION.md
Labels: hacktoberfest

#10 Form in HTML
  form.html
Labels: hacktoberfest

#8 Create first site.html
  CONTRIBUTION.md
  first site.html
Labels: hacktoberfest

#12 Lists in HTML
  lists.html
Labels: hacktoberfest

#11 My html
  CONTRIBUTION.md
  firstwebsite
Labels: hacktoberfest

#14 Create home.html
  home.html
Labels: hacktoberfest

#15 Create Navbar_in_HTML.html
  Navbar_in_HTML.html
Labels: hacktoberfest

#18 The A Href Attribute
  hrefattribute.html
Labels: hacktoberfest

#19 Added a food card project
  FoodCard/burger2.png
  FoodCard/foodCard.html
  FoodCard/style.css
Labels: hacktoberfest

#21 htmlrepo
  CONTRIBUTION.md
  htmlgame.htm
Labels: hacktoberfest

#20 added a landing page of gym website
  Gym Website Landing Page/images/dumble.png
  Gym Website Landing Page/images/gym1.jpg
  Gym Website Landing Page/images/gym2.jpg
  Gym Website Landing Page/images/gym3.jpg
  Gym Website Landing Page/images/gym4.jpg
  Gym Website Landing Page/images/gym5.jpg
  Gym Website Landing Page/images/img1.jpg
  Gym Website Landing Page/images/shouting-at-gym.jpg
  Gym Website Landing Page/index.html
  Gym Website Landing Page/style.css
Labels: hacktoberfest

#22 iframe_tags.html
  iframe_tags.html
Labels: hacktoberfest

#25 cv.html
  cv.html
Labels: hacktoberfest

#28 basic calculator made with HTML and Javascript wth the onclick event
  swap.html
Labels: hacktoberfest

#24 Create bgcolor.html
  bgcolor.html
Labels: hacktoberfest

#27 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: hacktoberfest

#23 Student'sForm.html
  Student'sForm.html
Labels: hacktoberfest

#29 Added HTML Codes
  CSS Password Generator.html
  Fantabulous 45 Loaders.html
  Fantastic 50 Dot Loaders.html
  Favourite 40 Loaders.html
  Hover Horror.html
  Login Form 1.html
  Login Form 2.html
Labels: hacktoberfest

#30 Added a Survey page
  survey_page.html
Labels: hacktoberfest

#17 Create UserProgressBar.html
  UserProgressBar.html
Labels: hacktoberfest

#16 Create ScriptForSudokuGame.html
  ScriptForSudokuGame.html
Labels: hacktoberfest

#31 hacktoberfest2022
  paragraph.html
Labels: hacktoberfest

#32 Created Shooting game code
  Shooting game code
Labels: hacktoberfest

#36 Added a calculator
  calculator.html
Labels: hacktoberfest

#37 Create code.html
  code.html
Labels: hacktoberfest

#38 Create code1.html
  code1.html
Labels: hacktoberfest

#39 Create prog.html
  prog.html
Labels: hacktoberfest

#42 check valid palindrome using javacsript
  Check valid palindrome.js
Labels: hacktoberfest

#34 3D touch button using html and css
  3dtouchbutton/3Dtouchbutton.css
  3dtouchbutton/3Dtouchbutton.html
Labels: hacktoberfest

#41 Create prog1.html
  prog1.html
Labels: hacktoberfest

#40 Create kitu.html
  kitu.html
Labels: hacktoberfest

#46 Create maxSubArray.java
  maxSubArray.java
Labels: hacktoberfest

#49 html
  Restaurant News & Announcements.html
Labels: hacktoberfest, hacksquad

#50 Create leftmostelementandreversing.html
  punya/leftmostelementandreversing.html
Labels: hacktoberfest

#52 Add files via upload
  index.html
Labels: hacktoberfest, hacksquad

#53 Add files via upload
  Stories About Your Restaurant.html
Labels: hacktoberfest, hacksquad

#54 Add files via upload
  gallery.html
Labels: hacktoberfest, hacksquad

#56 Create loginSignup.html
  loginSignup.html
Labels: hacktoberfest

#55 Simple Webpage using HTML & CSS
  webpage-main/README.md
  webpage-main/page.css
  webpage-main/page.html
  webpage-main/submit.html
Labels: hacktoberfest

#58 Create car_race.html
  car_race.html
Labels: hacktoberfest

#59 cakculator.html
  calculator.htm
Labels: hacktoberfest

#60 Create Counting_Sort.py
  Counting_Sort.py
Labels: hacktoberfest

#61 Rodrigo avendano
  CONTRIBUTION.md
  inverseArray.js
Labels: hacktoberfest

#63 Create farming.html
  farming.html
Labels: hacktoberfest, hacktoberfest2022 accepted

#62 Create sudoku solver.html
  sudoku solver.html
Labels: hacktoberfest, hacktoberfest2022 accepted
