Repository mr-robot-2008/html, pull requests merged in 2023-10, with the labels that each got.

#65 Create pass.html
  pass.html
Labels: hacktoberfest, hacktoberfest2022 accepted

#66 Create example.html
  example.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#68 Create maximum_subarray_solution.py
  maximum_subarray_solution.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#67 added solutions of 5 array problems
  Best time to buy and sell stock.cpp
  CONTRIBUTION.md
  Kth Largest Element in an Array.cpp
  Product of Array Except Self.cpp
  Search in Rotated Sorted Array.cpp
  Trapping Rain Water.cpp
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#64 Add QR Card Component
  QR Card Component/.gitignore
  QR Card Component/README-template.md
  QR Card Component/README.md
  QR Card Component/design/desktop-design.jpg
  QR Card Component/design/desktop-preview.jpg
  QR Card Component/design/mobile-design.jpg
  QR Card Component/images/favicon-32x32.png
  QR Card Component/images/image-qr-code.png
  QR Card Component/index.html
  QR Card Component/style-guide.md
  QR Card Component/style.css
Labels: bug, invalid, spam

#69 Create google clone index.html
  google_clone/index.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#73 3 sum.py
  3sum.py
  CONTRIBUTION.md
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#72 Create vendors_ecommerce_site.html
  vendors_ecommerce_site.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#71 Create cafe_website.html
  cafe_website.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#70 Create gym_website.html
  gym_website.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#78 Create profile.html
  profile.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#80 Create loginpage.html
  loginpage.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#79 added - Container with Most water problem
  Container With Most Water.cpp
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#81 Create LinearSearch.py
  LinearSearch.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#82 Create MatrixMultiplication.py
  MatrixMultiplication.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#83 Create QuickSort.c
  QuickSort.c
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#85 Create abdul's login form
  abdul's login form
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#86 armstrong.py
  armstrong.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#87 Create Ecommerce.html
  Ecommerce.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#92 Create longest_palidromic_substrng.py
  longest_palidromic_substrng.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#91 Create InorderTreeTraversal.py
  InorderTreeTraversal.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#90 Create SmallestDerangement.py
  SmallestDerangement.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#88 Create SequenceMatcher.py
  SequenceMatcher.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#95 Create long_prefix_sufix.py
  long_prefix_sufix.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#98 Create Tower of hanoi problem
  Tower of hanoi problem.java
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#97 Create Longest Increasing Subsequence.cpp
  Longest Increasing Subsequence.cpp
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#100 Create Matchstic.py
  Matchstic.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#99 added 3d cube
  3d_cube/index.html
  3d_cube/script.js
  3d_cube/styles.css
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#102 Create romannumber.py
  romannumber.py
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#104 Create alert.html
  alert.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#103 Create registerStudent.html
  registerStudent.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#106 Create coloumnTable.html
  coloumnTable.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#105 Create bootstrap website.html
  bootstrap website.html
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#107 Added Quiz Web
  Quiz/NOTES.html
  Quiz/img/WhatsApp Image 2023-06-05 at 16.18.02.jpeg
  Quiz/img/logo awal.png
  Quiz/img/revou.png
  Quiz/img/time-png-6175.png
  Quiz/img/yahoot.png
  Quiz/index.html
  Quiz/login script.js
  Quiz/login style.css
  Quiz/login.html
  Quiz/result.html
  Quiz/script quiz.js
  Quiz/style quiz.css
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted

#109 Create calculatpr.cpp
  calculatpr.cpp
Labels: hacktoberfest, hacktoberfest2022 accepted, hacktoberfest-accepted
